name: ci.yml

on:
  push:
    branches:
      - timeo

jobs:
  units-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du repository
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
            java-version: '17'
            distribution: 'corretto'
            architecture: x64
            cache: 'maven'

      - name: Maven temporary
        run: $env:Path = "D:\apache-maven-3.9.12\bin;$env:Path"

      - name: Run Units tests for calcul
        run: mvn clean test -f order-service/pom.xml -Dtest=com.devops.cicd.PricingServiceTest

      - name: Run Units tests for password
        run: mvn clean test -f order-service/pom.xml  -Dtest=com.devops.cicd.PasswordPolicyTest

  integration-test:
    needs: units-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du repository
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          architecture: x64
          cache: 'maven'

      - name: Run Integration tests
        run: mvn clean test -f order-service/pom.xml -Dtest=com.devops.cicd.PricingIntegrationTest

